name: TServerStats
version: ${project.version}
main: tect.host.TServerStats

author: Mine_Alex | Tect.host
api-version: '1.13'
website: tect.host

commands:
  tserverstats:
    aliases:
      - tstats